# Generated by Django 6.0.3 on 2026-03-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_department_studentid_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentid',
            old_name='std_id',
            new_name='student_id',
        ),
    ]
